### ISSUE TITLE
Error handler pointer getting garbage collected

### ISSUE THREAD

**Issue by bgarrood** [amomra/muParserNET#12]
I am using muparsernet in my multithreaded application and was getting random errors with following description;
A callback was made on a garbage collected delegate of type 'muParserNET!muParserNET.ErrorFuncType::Invoke'

I think because pointer to error handler in teh managed code gets garbage collected before getting called by unmanaged code.  In the managed code I have fixed by using GCHandle to lock the error function pointer from getting garbage collected.

**Comment by amomra** [comment]
Thanks for the feedback! I will fix it.

**Comment by amomra** [comment]
@bgarrood I did the fix based on your comment. Can you share the code that caused the error for me to perform some tests please? If not, can you do the tests then?

**Comment by bgarrood** [comment]
Hi.  
Thank you for updating.  Sorry my code is quite large and complex so not easy to share.  I am happy to test for you.
It runs about 8 threads, each using EvalBulk around 50 times for a single dataset.  These threads go through upwards of 100 datasets.
Is it updated on NuGet?  i would be very happy to test it with that, or otherwise if you can provide me with your updated dll?
Really nice job on muParserNET.  I looked at a lot of options and this came out by far the best.
Cheers

**Comment by eliukblau** [comment]
Hi! I have the same problem, but in my case is caused by execution of parser.Eval() inside the Tick event handler of a System.Windows.Form.Timer object. And only ocurrs if parser.Eval() throws some exception (expression empty, etc.)

@bgarrood Do you have the nuget package already compiled that you could share with me?

@amomra Or is there any possibility to update the official package in Nuget with this fix?

Unfortunately, I don't have an easy way to compile the code and generate the new nuget package by myself.

Thanks in advance!

Wonderful work, both of you. I use muParserNET in a government desktop app and this is best third party NEt library for eval maths. I agree with @bgarrood.

Kudos!

**Comment by eliukblau** [comment]
Hi! I have the same problem, but in my case is caused by execution of parser.Eval() inside the Tick event handler of a System.Windows.Form.Timer object. And only ocurrs if parser.Eval() throws some exception (expression empty, etc.)

@bgarrood Do you have the nuget package already compiled that you could share with me?

@amomra Or is there any possibility to update the official package in Nuget with this fix?

Unfortunately, I don't have an easy way to compile the code and generate the new nuget package by myself.

Thanks in advance!

Wonderful work, both of you. I use muParserNET in a desktop app and this wrapper is best third party NET library for eval maths. I agree with @bgarrood.

Kudos!

**Comment by amomra** [comment]
@eliukblau thank you! It's nice to have this kind of feedback. Also thanks @bgarrood for the help.

I'm sorry for taking so long to build the package... I will do this evening at home.

**Comment by amomra** [comment]
The NuGet package was updated. @bgarrood @eliukblau

**Comment by eliukblau** [comment]
@amomra Works perfectly fine. Thanks so much! 👍
